{
    "Message": "Download in progress...",
    "CompletionMessage": "Download Successful",
    "CompletionTimeout": 7,
    "OnSuccess": "/anup_first_mdk_app/Actions/AnupFirstMDKApp/Service/DownloadOffline.action",
    "_Type": "Action.Type.ProgressBanner"
}